

- name: run the write_file.py after it has already been transferred
  command: python3 /home/ubuntu/TwitterHarvesterV2.py "http://admin:admin@{{subnode1}}:5984/twitter"


- debug:
    msg: "http://admin:admin@{{subnode1}}:5984/twitter"
