
- name: create instance2
  os_server:
    name: "{{ instance2_name }}"
    image: "{{ instance_image }}"
    key_name: "{{ instance_key_name }}"
    flavor: "{{ instance_flavor }}"
    availability_zone: "{{ availability_zone }}"
    security_groups: "{{ sg_names }}"
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  register: os_instance2

- debug:
    msg: "Instance {{ instance2_name }} has been created. IP address is {{ os_instance2.openstack.public_v4 }}"
  when: os_instance2.openstack is defined

- name: create instance1
  os_server:
    name: "{{ instance1_name }}"
    image: "{{ instance_image }}"
    key_name: "{{ instance_key_name }}"
    flavor: "{{ instance_flavor }}"
    availability_zone: "{{ availability_zone }}"
    security_groups: "{{ sg_names }}"
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  register: os_instance1

- debug:
    msg: "Instance {{ instance1_name }} has been created. IP address is {{ os_instance1.openstack.public_v4 }}"
  when: os_instance1.openstack is defined

- name: create instance3
  os_server:
    name: "{{ instance3_name }}"
    image: "{{ instance_image }}"
    key_name: "{{ instance_key_name }}"
    flavor: "{{ instance_flavor }}"
    availability_zone: "{{ availability_zone }}"
    security_groups: "{{ sg_names }}"
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  register: os_instance3

- debug:
    msg: "Instance {{ instance3_name }} has been created. IP address is {{ os_instance3.openstack.public_v4 }}"
  when: os_instance3.openstack is defined



- name: create instance4
  os_server:
    name: "{{ instance4_name }}"
    image: "{{ instance_image }}"
    key_name: "{{ instance_key_name }}"
    flavor: "{{ master_instance_flavor }}"
    availability_zone: "{{ availability_zone }}"
    security_groups: "{{ sg_names }}"
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  register: os_instance4

- debug:
    msg: "Instance {{ instance4_name }} has been created. IP address is {{ os_instance4.openstack.public_v4 }}"
  when: os_instance4.openstack is defined



- name: Wait for connection
  wait_for:
    host: '{{ os_instance1.openstack.public_v4 }}'
    port: 22
    timeout : 120
    search_regex: OpenSSH
  when : os_instance1.openstack is defined

- name: Wait for connection
  wait_for:
    host: '{{ os_instance2.openstack.public_v4 }}'
    port: 22
    timeout : 120
    search_regex: OpenSSH
  when : os_instance2.openstack is defined

- name: Wait for connection
  wait_for:
    host: '{{ os_instance3.openstack.public_v4 }}'
    port: 22
    timeout : 120
    search_regex: OpenSSH
  when : os_instance3.openstack is defined

- name: Wait for connection
  wait_for:
    host: '{{ os_instance4.openstack.public_v4 }}'
    port: 22
    timeout : 120
    search_regex: OpenSSH
  when : os_instance4.openstack is defined



- name: Add host
  add_host:
    name: '{{ os_instance1.openstack.name }}'
    groups: COMP90024
  when: os_instance1.openstack is defined

- name: Add host
  add_host:
    name: '{{ os_instance2.openstack.name }}'
    groups: COMP90024
  when: os_instance2.openstack is defined

- name: Add host
  add_host:
    name: '{{ os_instance3.openstack.name }}'
    groups: COMP90024
  when: os_instance3.openstack is defined

- name: Add host
  add_host:
    name: '{{ os_instance4.openstack.name }}'
    groups: COMP90024
  when: os_instance4.openstack is defined

# - name: create file
#   become: yes
#   template:
#     src: hosts.j2
#     dest: "{{ node_inventory_file }}"

