
- name: Create instances
  os_server:
    name: '{{ item.name }}'
    image:  '{{ instance_image }}'
    key_name:  '{{ instance_key_name }}'
    flavor:  '{{ instance_flavor }}' 
    network:  '{{ network }}'
    availability_zone:  '{{ availability_zone }}'
    security_groups:  '{{ sg_names }}'
    volumes:  '{{ item.volumes }}'
    auto_floating_ip: yes
    wait: yes
    timeout : 600
    state : present
  loop: '{{ instances }}'
  register: os_instance



- debug: 
    msg: "instances {{ item.openstack.name }} has been created ,IP address is {{ item.openstack.public_v4 }}."
  loop: "{{ os_instance.results }}"
  when: item.openstack is defined


- name: create instance4
  os_server:
    name: "{{ instance4_name }}"
    image: "{{ instance_image }}"
    key_name: "{{ instance_key_name }}"
    flavor: "{{ master_instance_flavor }}"
    availability_zone: "{{ availability_zone }}"
    security_groups: "{{ sg_names }}"
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  register: os_instance4

- debug:
    msg: "Instance {{ instance4_name }} has been created. IP address is {{ os_instance4.openstack.public_v4 }}"
  when: os_instance4.openstack is defined



- name: Wait for connection
  wait_for:
    host: '{{ item.openstack.public_v4 }}'
    port: 22
    timeout : 120
    search_regex: OpenSSH
  loop : '{{ os_instance.results }}'
  when : item.openstack is defined




- name: Add host
  add_host:
    name: '{{ item.openstack.name }}'
    groups: COMP90024
  loop : '{{ os_instance.results }}'
  when: item.openstack is defined
