---
 
- name: Install multi python packages with version specifiers
  pip:
    name:
      - certifi==2020.12.5
      - chardet==4.0.0
      - click==7.1.2
      - idna==2.10
      - joblib==1.0.1
      - nltk==3.6.2
      - numpy==1.20.3
      - oauthlib==3.1.0
      - PySocks==1.7.1
      - python-dateutil==2.8.1
      - PyYAML==5.4.1
      - regex==2021.4.4
      - requests==2.25.1
      - requests-oauthlib==1.3.0
      - six==1.16.0
      - textblob==0.15.3
      - tqdm==4.60.0
      - tweepy==3.10.0
      - urllib3==1.26.4





# - name: Start Twitter.py at background using nohup
#   become: yes
#   shell: python3 /home/ubuntu/twitter.py 

# - name: Run Py script

#   command: /home/ubuntu/twitter.py 
#   become: yes
#   become_user: root



# - name: execute install script
#   script: ./Twitter.py 

- name: Transfer TwitterHarvesterV2.py.
  become: yes
  copy:
    src: ../../../../Harvest/TwitterHarvesterV2.py 
    dest: /home/ubuntu/
    mode: 0777

- name: Transfer Config_Ins_1.json.
  become: yes
  copy:
    src: ../../../../Harvest/Config_Ins_1.json
    dest: /home/ubuntu/
    mode: 0777

- name: Transfer Config_Ins_2.json.
  become: yes
  copy:
    src: ../../../../Harvest/Config_Ins_2.json
    dest: /home/ubuntu/
    mode: 0777

- name: Transfer Config_Ins_3.json.
  become: yes
  copy:
    src: ../../../../Harvest/Config_Ins_3.json
    dest: /home/ubuntu/
    mode: 0777


- name: Transfer requirements.txt.
  become: yes
  copy:
    src: ../../../../Harvest/requirements.txt 
    dest: /home/ubuntu/
    mode: 0777

- name: run the requirements.txt
  command: python3 -m pip install --user -r /home/ubuntu/requirements.txt


