---
volumes:
  - device: /dev/vdb
    mountpoint: /data
  - device: /dev/vdc
    mountpoint: /var/lib/docker

# CouchDB configuration
user: admin
pass: admin
VERSION: '3.1.1'
cookie: 'a192aeb9904e6590849337933b000c99'
uuid: '5CBC6EFF-45E9-4981-B300-D40782BA0B26'