
availability_zone: melbourne-qh2-uom
network: qh2-uom-internal


volumes:
  - vol_name: vol-1
    vol_size: 125
  - vol_name: vol-2
    vol_size: 125
  - vol_name: vol-3
    vol_size: 125
  - vol_name: vol-4
    vol_size: 125


security_groups:
  - name: ssh
    description: "security groups for ssh"
    protocol : tcp
    port_range_min : 22
    port_range_max : 22
    remote_ip_prefix : 0.0.0.0/0

  - name: http
    description: "security groups for http"
    protocol : tcp
    port_range_min : 80
    port_range_max : 80
    remote_ip_prefix : 0.0.0.0/0


  - name: couchdb1
    description: "open port for couchdb1"
    protocol : tcp
    port_range_min : 5984
    port_range_max : 5984
    remote_ip_prefix : 0.0.0.0/0

  - name: couchdb2
    description: "open port for couchdb2"
    protocol : tcp
    port_range_min : 4369
    port_range_max : 4369
    remote_ip_prefix : 0.0.0.0/0

  - name: couchdb3
    description: "open port for couchdb3"
    protocol : tcp
    port_range_min : 9100
    port_range_max : 9100
    remote_ip_prefix : 0.0.0.0/0


instances:
  - name: ins-1
    volumes: 'vol-1'
  - name: ins-2
    volumes: 'vol-2'
  - name: ins-3
    volumes: 'vol-3'


instance4_name: ins-4
instance4_volumes: 'vol-4'

instance_image :  f8b79936-6616-4a22-b55d-0d0a1d27bceb
instance_key_name : group60
master_instance_flavor : uom.mse.1c4g
instance_flavor : uom.mse.2c9g






