
 #Perform CouchDB configuration on all hosts except Masternode
- hosts: subnode1:subnode2:subnode3
  vars_files:
    - host-vars/couchdb.yaml
    - host-vars/proxy.yaml
  gather_facts: true

  roles:
    - role: coughdb-install



 # Perform CouchDB configuration on subnode1
- hosts: subnode1
  vars_files:
    - host-vars/couchdb.yaml
    - host-vars/proxy.yaml
  gather_facts: true

  roles:
    - role: coughdb-setup