- name: Transfer and execute a script.
  become: yes
  copy:
    src: ./aurin.sh
    dest: /home/ubuntu/
    mode: 0777



- name: Let's copy our executable script to remote location, execute script .
  remote_user: root
  become: yes
  command: sh /home/ubuntu/aurin.sh


- debug:
    msg: "subnode1"
